module.exports={
    ADMIN_COLLECTION:'admin',
    AUTO_COLLECTION:'auto',
    PAYMENT_COLLECTION:'payment',
    TRAVELCHARGE_COLLECTION:'travelrate',
    TRAVELPLACES_COLLECTION:'tavelplaces',
    USER_COLLECTION:'users',
    BOOKING_COLLECTION:'books',
    DRIVE_COLLECTION:'drives'
}